name = "aaa"
license = "MIT"
licenselink = "Link to theme's license"
description = "Theme description"
homepage = "https://qajf.github.io/blogtest/"
tags = ["blog", "company"]
features = ["some", "awesome", "features"]
min_version = "0.59.1"

# If the theme has multiple authors
authors = [
  {name = "Name of author", homepage = "Website of author"},
  {name = "Name of author", homepage = "Website of author"}
]

# If the theme has a single author
[author]
    name = "Your name"
    homepage = "https://qajf.github.io/blogtest/"

# If porting an existing theme
[original]
    author = "Name of original author"
    homepage = "https://qajf.github.io/blogtest/"
    repo = "Link to source code of original theme"
